envVariables.js
module/userProjects/helper.js

Initial changes : ENV changes and project add api changes

---

module/project/templates/helper.js
module/project/templates/validator/v1.js

projectTemplates APIs change

---

generics/middleware/authenticator.js
module/project/templateTasks/helper.js

TaskTemplate API changes bulkCreate && update, Authenticator changes

---

module/project/templates/helper.js
module/project/templates/validator/v1.js

importProjectTemplate API change

---

controllers/v1/project/templates.js
module/project/templates/helper.js

project templates list with pagination and search

---

.env.sample
controllers/v1/files.js
envVariables.js
generics/constants/api-responses.js
generics/helpers/utils.js
generics/services/cloudStorage.js
module/files/helper.js
module/files/validator/v1.js
package.json

file upload feature added

---

.env.sample

env sample change

---

.dockerignore
.env.sample
Dockerfile
app.js
config/db/mongodb.js
docker-compose.yml
generics/middleware/authenticator.js
package.json
routes/index.js

Initial changes for making compatible with user service & interface

---

.env.sample
envVariables.js
generics/services/entity-management.js
module/programs/helper.js

envVariable file updation

---

module/userProjects/helper.js

entityDocument query change

---

controllers/v1/programs.js
controllers/v1/project/templateTasks.js
controllers/v1/project/templates.js
module/programs/validator/v1.js
module/solutions/validator/v1.js

Forms api changes

---

envVariables.js

new env variable added

---

envVariables.js

env variable file changes

---

module/userProjects/helper.js

solution related changes in userProjects/details API

---

controllers/v1/admin.js
generics/constants/api-responses.js
generics/helpers/utils.js
module/admin/helper.js

db find api added

---

databaseQueries/admin.js
module/admin/helper.js

dbFind fix

---

generics/middleware/authenticator.js
module/files/helper.js
module/solutions/helper.js

preSignedUrl reponse struct fix & files merged from develop

---

envVariables.js
module/solutions/helper.js

targetSolutions API fix

---

generics/helpers/common_handler.js
module/userProjects/helper.js
views/improvementProjectTaskTemplate.ejs
views/improvementProjectTemplate.ejs

Share api report logic fix: projectPdf&projectTaskPdf

---

envVariables.js

envVariables file changes

---

generics/constants/api-responses.js
module/cloud-services/files/helper.js
module/files/helper.js

cloud response format changes

---

module/solutions/helper.js
module/userProjects/helper.js

"changes-solution-details-api"

---

module/userProjects/helper.js

"changes-soultion-details"

---

module/userProjects/helper.js

cloud-realted changes in userProjects/detail API

---

envVariables.js

default value fix in envVariable file

---

module/solutions/helper.js

debug consoles added

---

module/solutions/helper.js

console logs added

---

module/profile/helper.js
module/project/templates/helper.js
module/solutions/helper.js
module/userProjects/helper.js

Develop branch merge

---

module/solutions/helper.js
module/userProjects/helper.js

userProjects/details API fix

---

generics/middleware/authenticator.js

token-variable-name-fix

---

generics/helpers/common_handler_v2.js

"fix-for-detail-View"

---

module/programs/helper.js
module/solutions/helper.js
module/userProjects/helper.js

deepLink flow verified

---

module/userProjects/helper.js

importFromLibrary API fix

---

generics/helpers/common_handler_v2.js

"fix-details-view-api"

---

generics/constants/api-responses.js
module/profile/helper.js
module/userProjects/helper.js

userService.profile data filtering fix

---

controllers/v1/solutions.js
module/solutions/helper.js

Targeted Solutions API Change For Dynamic Scoping

---

module/reports/helper.js

Report api

---

generics/helpers/utils.js
models/programs.js
module/solutions/helper.js

Date fields fix

---

.env.sample
envVariables.js

env variables updation in envVariable.js & env.sample file

---

module/reports/validator/v1.js

"validation-for-getProgramsByEntity"

---

module/solutions/helper.js

project-data extraction fix

---

module/solutions/helper.js

targeted projects filtering fixed

---

module/userProjects/helper.js
module/userProjects/validator/v1.js

"validator-added-for-userProjectAdd"

---

module/project/templates/helper.js

bug fix template details api

---

envVariables.js

envVariable file updated

---

models/configurations.js

dummy cofiguration model added to avoid mongo error

---

module/solutions/helper.js

changes added to discovereByMe filter for targeting projects

---

module/solutions/helper.js
module/solutions/validator/v1.js

targetting level changes to accept dynamic data

---

module/certificateTemplates/helper.js

createSvg api changes

---

generics/helpers/common_handler.js

cloud uploads for both share api & certificate api fixed

---

module/userProjects/helper.js

link missing from project data - fix nTu deeplink flow

---

generics/helpers/common_handler.js
module/userProjects/helper.js

Develop to staging build

---

module/userProjects/helper.js

nTU certificate fix

---

controllers/v1/programs.js
controllers/v1/solutions.js
databaseQueries/programs.js
databaseQueries/solutions.js
generics/constants/api-responses.js
generics/helpers/common_handler.js
models/programs.js
module/programs/helper.js
module/programs/validator/v1.js
module/project/templates/helper.js
module/solutions/helper.js
module/solutions/validator/v1.js

Solution scope fix

---

module/userProjects/helper.js

remove certificate object for private projects

---

module/solutions/helper.js
module/userProjects/helper.js

certificate hide nTu

---

models/projects.js

model name change

---

Project-Service-implementation-Script/main.py

"changes-for-csv"

---

module/solutions/helper.js

project fetch using search filter fixed

---

controllers/v1/solutions.js
module/solutions/helper.js

new field introduced to fetching of projects

---

module/profile/helper.js

"added-externalId"

---

module/solutions/helper.js

projects fetch response fixed

---

module/userProjects/helper.js

certificateReissue api eligible field updated

---

Project-Service-implementation-Script/common_config/config.ini
Project-Service-implementation-Script/main.py

"added-certifcate"

---

module/cloud-services/files/helper.js

cloud-services apis response fixed

---

module/userProjects/helper.js
views/improvementProjectTaskTemplate.ejs
views/improvementProjectTemplate.ejs

share-api image preview in pdf fixed

---

module/userProjects/helper.js

removed certificate keys from project in library flow

---

generics/helpers/common_handler_v2.js

"colour-fixed"

---

Project-Service-implementation-Script/common_config/config.ini
Project-Service-implementation-Script/main.py

"added-dates-subtask-task"

---

generics/helpers/common_handler_v2.js

"colour-fixed-report"

---

module/forms/validator/v1.js

updated the validations for forms apis

---

module/userProjects/helper.js

changed code to use _id instead of value keyword

---

module/userProjects/helper.js

verifyCertificate-api getDownloadableUrl response validation fix

---

generics/middleware/authenticator.js

Autherization Logic Upgraded To Extract Token Data Based On Config

---

Project-Service-implementation-Script/common_config/config.ini
Project-Service-implementation-Script/main.py

"added-Recommended-for"

---

generics/helpers/utils.js
module/userProjects/helper.js

changes made to handle special characters appearing in project-title

---

module/userProjects/helper.js

"Fix-for-1890"

---

module/userProjects/helper.js

update character limit for user-name and project-title

---

api-doc/Elevate-Project.postman_collection.json
api-doc/Elevate-project LOCAL.postman_environment.json
api-doc/api-doc.yaml

"API-DOC-FOR-Project"

---

module/userProjects/helper.js

username & project-title chars limit lowered

---

models/projects.js
models/solutions.js

removed redundant fields and restructured projects model

---

Dockerfile

changes made to Dockerfile

---

documentation/1.0.0/dockerized/scripts/mac-linux/add_sample_project_entity_data.sh

change in add sample data

---

README.md
documentation/1.0.0/native/scripts/linux/check-dependencies.sh
documentation/1.0.0/native/scripts/linux/citus_setup.sh
documentation/1.0.0/native/scripts/linux/install-dependencies.sh
documentation/1.0.0/native/scripts/linux/uninstall-dependencies.sh

Service setup child 2

---

README.md

Service setup

---

README.md

alignment fix

---

README.md

env path change

---

documentation/1.0.0/dockerized/docker-compose-project.yml

docker compose file change

---

README.md

env files downloable links updated

---

module/programs/helper.js

static data added for programs list & details apis

---

constants/interface-routes/configs.json
controllers/v1/users.js
generics/constants/api-responses.js
generics/constants/common.js
module/programs/helper.js
module/userProjects/helper.js
module/users/helper.js
module/users/validator/v1.js

user solutions api enabled

---

constants/interface-routes/configs.json

config updated

---

documentation/1.0.0/dockerized/scripts/windows/entity-project-sample-data.bat

"entity-project-insert"

---

controllers/v1/solutions.js
module/solutions/helper.js
module/userProjects/helper.js

fetching projects/solutions based on entityId key handled

---

module/users/helper.js

program-listing count field updated

---

module/users/helper.js

handeld an edge while setting count for users/programs api

---

module/reports/validator/v1.js

"getProgramsByEntity-API"

---

constants/interface-routes/configs.json

"added-route"

---

Project-Service-implementation-Script/README.md
Project-Service-implementation-Script/main.py

"can-add-multiple-projects"

---

documentation/1.0.0/dockerized/docker-compose-project.yml

interface service image update

---

Project-Service-implementation-Script/main.py

"Get-certificate-withOnly-task"

---

README.md
documentation/1.0.0/dockerized/scripts/mac-linux/setup_project.sh

Readme review changes

---

documentation/1.0.0/dockerized/scripts/mac-linux/add_sample_project_entity_data.sh

updated the script to add tasks to projects

---

README.md
documentation/1.0.0/dockerized/scripts/mac-linux/import_forms_mongo.sh
documentation/1.0.0/dockerized/scripts/windows/import_forms_mongo.bat

script for default form inerstion for portal configuration into mongo

script for default form inerstion for portal configuration into mongo

---

documentation/1.0.0/dockerized/scripts/mac-linux/add_sample_project_entity_data.sh

script restored

---

module/solutions/helper.js

projects fetching query updated

---

app.js
config/globals.js
package.json

file-import issue fixed

---

module/userProjects/helper.js

project-fetch for mutiple user fixed

---

README.md

removed MentorED wordings from readme file

---

documentation/1.0.0/dockerized/docker-compose-project.yml

docker image updates

---

Project-Service-implementation-Script/main.py

"Implimentation-script-to-map-duplicate-entity"

---

constants/interface-routes/configs.json
controllers/v1/projectAttributes.js
databaseQueries/projectAttributes.js
generics/constants/api-responses.js
generics/constants/common.js
generics/constants/endpoints.js
generics/middleware/authenticator.js
generics/services/entity-management.js
models/project-attributes.js
module/projectAttributes/helper.js
module/projectAttributes/validator/v1.js

mi 2.0 filter api

---

constants/interface-routes/configs.json

fix for  bug in wishlist routes

---

module/projectAttributes/helper.js

FE requirment in filter api

---

controllers/v1/project/templates.js
controllers/v1/userProjects.js
controllers/v1/users.js
generics/helpers/utils.js
module/library/categories/helper.js
module/programs/helper.js
module/project/templates/helper.js
module/userProjects/helper.js
module/users/helper.js
module/wishlist/helper.js

multilingual changes for sprint 1

---

constants/interface-routes/configs.json
controllers/v1/library/categories.js
controllers/v1/template.js
models/programs.js
models/project-categories.js
models/project-template-tasks.js
models/project-templates.js
models/projects.js
models/solutions.js
module/library/categories/helper.js
module/template/validator/v1.js

 Feature/mi2.0/project category listing

---

constants/interface-routes/configs.json

config correction

---

controllers/v1/template.js
models/project-templates.js
module/library/categories/helper.js

category changes + model changes

---

controllers/v1/project/templates.js
generics/constants/api-responses.js
models/project-templates.js
module/evidences/helper.js
module/project/templates/helper.js
module/solutions/helper.js
module/userProjects/helper.js

projectTemplate changes for MI-2.0

---

databaseQueries/userExtension.js
module/project/templates/helper.js

wishlist modification

---

module/userProjects/helper.js

importCount logic handled

---

controllers/v1/project/templateTasks.js
module/project/templateTasks/helper.js
module/project/templates/helper.js
module/userProjects/helper.js

templateTasks/bulkCreate api changes for MI-2.0

---

module/userProjects/helper.js

bug fix list api

---

module/library/categories/helper.js

response changes for projects listing made

---

.env.sample
envVariables.js
generics/helpers/utils.js

default-category to crete projectTemplates handled

---

generics/helpers/utils.js

Chore/mi 2.0 changes

---

module/userProjects/helper.js

userProjectlist res changes

---

module/library/categories/helper.js

signedUrls for evidences handled

---

generics/constants/common.js
module/library/categories/helper.js

filter fix for durations

---

generics/helpers/utils.js
module/userProjects/helper.js

Bug fixes/translations

---

generics/constants/common.js
generics/helpers/utils.js
module/evidences/helper.js
module/library/categories/helper.js
module/project/templates/helper.js
module/userProjects/helper.js

Mi 2.0 develop

---

module/project/templates/helper.js

evidence attachment handled

---

MI-2.0-Implementation-Script/main.py
Project-Service-implementation-Script/main.py

"added-validations"

---

MI-2.0-Implementation-Script/main.py

"Is-Working-without-evidence-also"

---

module/userProjects/helper.js

commited non required code

---

constants/interface-routes/configs.json
controllers/v1/userProjects.js
generics/constants/api-responses.js
models/projects.js
module/userProjects/helper.js
module/userProjects/validator/v1.js

update api for userproject with task and reflection

---

.env.sample
envVariables.js
generics/constants/api-responses.js
generics/helpers/utils.js
generics/middleware/authenticator.js
models/programs.js
models/projects.js
models/solutions.js
module/solutions/helper.js
module/userProjects/helper.js
module/userProjects/validator/v1.js

implementation of userProjects/add api

---

module/userProjects/helper.js

relfectionEnabled info handled for /userProjects/details api

---

constants/interface-routes/configs.json

"added-interface-url-for-addStory"

---

constants/interface-routes/configs.json
controllers/v1/userProjects.js
generics/middleware/authenticator.js
module/userProjects/helper.js

"added-put-method"

---

module/userProjects/helper.js

adding completed date in userProject listing api

---

module/userProjects/helper.js

"attachment-removed-from-addStory"

---

.env.sample
envVariables.js
generics/middleware/authenticator.js

Token bearer configurable and fix for envVaribale

---

generics/middleware/authenticator.js

token config fix

---

controllers/v1/template.js
module/library/categories/helper.js

bugFixes for listing basedon userRoles

---

module/userProjects/helper.js

programName key added to userProjects/list api response

---

module/userProjects/helper.js

date specific fields handled

---

module/userProjects/helper.js

test commit

---

module/project/templateTasks/helper.js

tanslation changes for templateTasks

---

controllers/v1/library/categories.js
models/programs.js
models/projects.js
module/library/categories/helper.js
module/solutions/helper.js
module/userProjects/helper.js

Chore/mi 2.0 changes 2

---

module/userProjects/helper.js

endDate bugFixes

---

models/programs.js
module/solutions/helper.js
module/userProjects/helper.js

reverted conversation changes at programs level

---

module/projectAttributes/validator/v1.js

Bug fixes/dec23

---

.env.sample
envVariables.js
generics/constants/common.js
generics/keycloakPublicKeys/.gitignore
generics/middleware/authenticator.js

authenticator changes to handle 2 ways of user login

---

models/projects.js

project-model changes

---

module/library/categories/helper.js

added evidences in list res

---

module/userProjects/helper.js
module/userProjects/validator/v1.js

userProjects/add api reponse & validation changes

---

generics/helpers/utils.js

Handle duration date

---

module/library/categories/helper.js

if condition added to fix issue if category is not found

---

README.md

login creds updated in readme guide

---

module/projectAttributes/helper.js
module/projectAttributes/validator/v1.js

validations updated for projectAttributes/update api

---

module/userProjects/helper.js

Convert solutionId to ObjectID for MongoDB compatibility

---

module/userProjects/helper.js

reverted the previous code changes w.r.t. ObjectID

---

module/wishlist/helper.js

count for wishlist/list api updated

---

module/userProjects/helper.js

mongo-update api flag updated

---

module/solutions/helper.js

startDate verification for targetedSolutions api updated

---

constants/interface-routes/configs.json

added orchestration changes for userProjects/list api

---

constants/interface-routes/configs.json

config file updated for orchestration

---

constants/interface-routes/elevate-project/configs.json

separate route config file for elevate-project added

---

constants/interface-routes/sunbird-project/configs.json

sunbird-proj package routes file created

---

constants/interface-routes/sunbird-project/configs.json

sunbird-project routes config file updated

---

module/project/templates/validator/v1.js

validation handle making metainformation optional

---

constants/interface-routes/sunbird-project/configs.json
controllers/v1/profile.js
generics/services/entity-management.js
generics/services/users.js
module/profile/helper.js
module/solutions/helper.js

Sunbird npm check

---

constants/interface-routes/sunbird-project/configs.json
controllers/v1/profile.js
generics/services/users.js
module/profile/helper.js
module/solutions/helper.js

Reverts ELEVATE-Project/project-service#390

Revert "Sunbird npm check"

---

constants/interface-routes/sunbird-project/configs.json
controllers/v1/profile.js
generics/services/users.js
module/profile/helper.js

profile read api changes

---

generics/services/users.js

revert change

---

module/userProjects/helper.js

added error message

---

generics/services/users.js
models/forms.js
module/forms/helper.js

forms model changes and error handling achieved

---

constants/interface-routes/sunbird-project/configs.json

route configs updated for sunbird-project pkg

---

constants/interface-routes/elevate-project/configs.json

rate limit added to files/download api

---

.env.sample
envVariables.js
generics/middleware/authenticator.js

authenticator changes to capture orgId from req.header

---

controllers/v1/userProjects.js
module/userProjects/helper.js

userToken passed as a param

---

migrations/sunbirdSaasDBmigration.js

changes in sunbird migration script

---

constants/interface-routes/sunbird-project/configs.json

eliminated dependency of sunbird-location service

---

constants/interface-routes/elevate-project/configs.json

org-admin createUser config updated

---

constants/interface-routes/elevate-project/configs.json

"index-url-added"

---

constants/interface-routes/elevate-project/configs.json

rate limit added to entities/details api

---

MI-2.0-Implementation-Script/main.py
Project-Service-implementation-Script/main.py
Sunbird-Project-Service-implementation-Script/main.py

"added-with-mutli-score"

---

MI-2.0-Implementation-Script/main.py
Project-Service-implementation-Script/main.py
Sunbird-Project-Service-implementation-Script/main.py

"program-tile-fix"

---

constants/interface-routes/elevate-project/configs.json

"added-targeted-routes"

---

Project-Service-implementation-Script/main.py
controllers/v1/reports.js
generics/middleware/authenticator.js
module/reports/helper.js

handling tenant/org changes in reports

---

constants/interface-routes/elevate-project/configs.json
controllers/v1/dataPipeline.js
module/dataPipeline/helper.js
module/dataPipeline/validator/v1.js

Kafka push api

---

generics/middleware/authenticator.js
module/solutions/helper.js

"auth-changes-for-soln"

---

generics/middleware/authenticator.js
module/solutions/helper.js

Develop to staging

---

generics/middleware/authenticator.js
module/solutions/helper.js

bugfix:solution fetch link

---

.env.sample
controllers/v1/solutions.js
envVariables.js
generics/constants/api-responses.js
module/solutions/helper.js

fetch link api changes

---

generics/helpers/utils.js
generics/middleware/addTenantAndOrgInRequest.js
generics/middleware/authenticator.js
migrations/updateAllCollections/transformOrgIdsFields.js
models/certificateBaseTemplates.js
models/certificateTemplates.js
models/forms.js
models/programs.js
models/project-categories.js
models/project-template-tasks.js
models/project-templates.js
models/solutions.js
module/certificateBaseTemplates/helper.js
module/certificateTemplates/helper.js
module/forms/helper.js
module/library/categories/helper.js
module/profile/helper.js
module/programs/helper.js
module/project/templateTasks/helper.js
module/project/templates/helper.js
module/solutions/helper.js
module/userProjects/helper.js
module/users/helper.js

savePoint-May-26

---

generics/middleware/addTenantAndOrgInRequest.js

"soln-details-fix"

---

module/solutions/helper.js

response update for targetedSolutions api

---

module/programs/helper.js

multi-org feature enabled for users/programs api

---

migrations/updateAllCollections/updateScopeData.js

updated migration script to add array strings in scope

---

module/programs/helper.js
module/solutions/helper.js

updated search filter query

---

generics/middleware/authenticator.js

added-orgId

---

module/solutions/helper.js

fetch-link-api-fix

---

generics/constants/common.js
generics/helpers/utils.js

orgId 'all' filter fix

---

module/programs/helper.js
module/solutions/helper.js

scope-change-for-soln-prog

---

module/solutions/helper.js

bugfix comma missing

---

models/project-template-tasks.js
module/project/templateTasks/helper.js

Project-as-a-task

---

deployment/ansible.yml

ansible update for config file

---

deployment/ansible.yml

anisble updated to develop

---

LICENSE

feat:license update

---

constants/interface-routes/elevate-project/configs.json

added-for-entity

---

migrations/pushProjectsToKafka/pushProjectsToKafka.js

Project kafkapush

---

migrations/pushProjectsToKafka/pushProjectsToKafka.js

optimization

---

constants/interface-routes/elevate-project/configs.json
controllers/v1/userProjects.js
generics/services/entity-management.js
models/solutions.js
module/entities/helper.js
module/userProjects/helper.js

project-consumption against entity implemented

---

.github/workflows/docker-image.yml

enable dockr publish work flow

---

module/entities/helper.js
module/userProjects/helper.js
module/userProjects/validator/v1.js

restricted entityId & entityInformation from payload

---

.env.sample
envVariables.js
healthCheck/README.md
healthCheck/health.config.js
package.json

kafka-topic-change

---

migrations/correctScopeOrgValues/correctScopeOrgValues.js

migration script to fix scope.organizations

---

release-notes/staging/release-3.3.6.8.md
release-notes/staging/release-3.3.6.9.md

release notes added for staging releases

---

generics/middleware/authenticator.js

feat:deep link issue fix
